[JARS-88] Start one process for celery beat
diging/ansible-amphora-role pull request #1
Opened 2017-12-12 18:19 UTC by hashknot

Start celery beat in a separate independent
process.

2017-12-16 21:07 UTC, prnvshrn approved these changes

2018-01-02 19:41 UTC, jdamerow requested changes
just some small changes

2018-01-02 19:41 UTC, jdamerow commented on files/celery_beat_start
> +DJANGO_CELERY_MODULE=jars.celery                     # WSGI module name
let's remove the ones that are not used

2018-01-02 19:41 UTC, jdamerow commented on files/celery_beat_start
> +DJANGO_CELERY_MODULE=jars.celery                     # WSGI module name
and let's adjust the NAME variable to accurately reflect which process is started

2018-01-02 21:31 UTC, hashknot commented
- Removed unnecessary variable definitions
- Updated NAME variable definition

2018-01-02 22:45 UTC, jdamerow approved these changes

2018-01-02 22:47 UTC, merged